INSERT INTO warehouse (warehouse_name,street,city,sqr_m2, version) VALUES
	 ('Føtex','Jernbanegade','Roskilde',3800, 8),
	 ('Bilka','Torvet','Ishøj',4000, 11),
	 ('Elgiganten','Fabriksparken','Roskilde 3',3400, 8),
	 ('Bauhaus','Industrivej','Roskilde',4500, 5),
	 ('Power','Hovedvejen 123','Glostrup',3500, 4);



insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Zooveo', 'Welch', 'Yoshkar-Ola', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Eayo', 'Welch', 'Aylmer', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Cogidoo', '2nd', 'Jiangzhou', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Linktype', 'Green', 'Baoquan', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Npath', 'Sheridan', 'Riit', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Vinder', 'Artisan', 'Gaizhou', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Tagpad', 'Troy', 'Modis', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Browsebug', 'Esker', 'Cipasung', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Meedoo', 'Dawn', 'Hengjie', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Skynoodle', 'Buhler', 'Castelo', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Minyx', 'Schiller', 'Göteborg', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Youfeed', 'Manitowish', 'Hornówek', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Realmix', 'Meadow Ridge', 'Capatárida', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Rhycero', 'Mosinee', 'Savski Venac', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Quatz', 'Marcy', 'Jinshanzui', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Quire', 'David', 'Buchou', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Zooveo', 'Lerdahl', 'Morong', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Riffpath', 'Truax', 'Barengkok', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Quaxo', 'Grayhawk', 'Svyetlahorsk', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Realfire', 'Lerdahl', 'Lebak', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Plajo', 'Arrowood', 'Amper', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Topicware', 'Rigney', 'Tekikbanyuurip', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Twitterworks', 'Vermont', 'Antonina', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Yacero', 'Rigney', 'Leifeng', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Npath', 'Jana', 'Saint-Rémi', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Skyndu', 'Ridgeview', 'Wushan', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Jaxnation', 'Sachs', 'Rosso', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Blogspan', 'Hermina', 'Babug', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Browsetype', 'Little Fleur', 'Escada', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Jayo', 'Leroy', 'Poá', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Avamba', 'Westerfield', 'Longhua', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Centidel', 'Mockingbird', 'Kanshan', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Lazzy', 'Melrose', 'Gambut', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Thoughtblab', 'Straubel', 'Barcin', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Jabbertype', 'Village Green', 'Lianyun', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Janyx', 'Scoville', 'Daguyun', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Einti', 'Ridgeview', 'Bečej', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Edgeify', 'Sutherland', 'Bistrinci', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Tambee', 'Bartelt', 'Labrador City', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Jaxbean', 'Pepper Wood', 'Antony', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Izio', 'Amoth', 'Iquique', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Photofeed', 'Debra', 'Baikouquan', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Einti', 'Leroy', 'Catujal Velho', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Wikizz', 'Reindahl', 'Al Fandaqūmīyah', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Aimbo', 'Longview', 'Krasnyy Yar', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Mydo', 'Petterle', 'Gąbin', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Plajo', 'Grim', 'Curridabat', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Zoomdog', 'Dexter', 'Di Linh', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Yakijo', 'Bay', 'Rionegro', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Plajo', 'Knutson', 'Ditang', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Browsedrive', 'Holmberg', 'Vicente Guerrero', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Youbridge', 'Tomscot', 'Gucun', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Livefish', 'Prairieview', 'Fuwah', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Skyble', 'Sundown', 'Hallstahammar', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Livetube', 'Ryan', 'Dateng', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Plambee', 'Boyd', 'Ai Tu', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Youopia', 'Roxbury', 'Pantaibesar', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Photojam', 'Susan', 'El Arañado', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Meezzy', 'Nelson', 'Yuanyang Zhen', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Thoughtbridge', 'Eggendart', 'San Francisco', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Trupe', 'Kinsman', 'Erong', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Jetwire', 'Spaight', 'Rancabelut', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Browsebug', 'Muir', 'Camaçari', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Meembee', 'Grover', 'Teupasenti', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Abata', 'Basil', 'Rehoboth', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Geba', 'Grasskamp', 'Prachin Buri', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Viva', 'Manitowish', 'Cangshi', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Meemm', 'Butternut', 'Bolyarovo', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Quinu', 'Stoughton', 'Tambakrejo', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Wordify', 'Trailsway', 'Ubon Ratchathani', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Photojam', 'Bartillon', 'Ciénega', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Eare', 'Sachtjen', 'Kudamatsu', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Centidel', 'Forest Dale', 'Nūrābād', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Eire', 'Ridgeview', 'Longquan', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Bluejam', 'Dovetail', 'Taiping', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Edgepulse', 'Fordem', 'Chengqu', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Plajo', 'Almo', 'Bhamdoûn el Mhatta', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Yodoo', 'Straubel', 'Kotel’va', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Rhycero', 'Leroy', 'Castres', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Riffwire', 'Red Cloud', 'Niš', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Livetube', 'Hauk', 'Sandefjord', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Feedspan', 'Meadow Valley', 'Naro-Fominsk', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Youtags', 'Victoria', 'Lgota Wielka', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Skyba', 'Clemons', 'Gilin', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Browsezoom', 'Golden Leaf', 'Ngepoh Kidul', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Flipstorm', 'Meadow Ridge', 'Kabarnet', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Rhybox', 'Loftsgordon', 'Mólos', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Bluezoom', 'Sundown', 'Hodoš', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Voolith', 'Steensland', 'Xianhe', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Meemm', 'Carey', 'Tolitoli', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Babbleset', 'Fordem', 'Sūq Şirwāḩ', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Cogilith', 'Evergreen', 'Dobřív', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Bubbletube', 'Pond', 'Kónitsa', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Tazz', 'Pawling', 'Cigaleuh Kulon', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Fliptune', 'Cherokee', 'Laixi', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Eabox', 'Donald', 'Tambo', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Browsebug', 'Garrison', 'Lysá nad Labem', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Tagfeed', 'Spohn', 'Pangrumasan', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Yodoo', 'Express', 'Letuyi', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Gabspot', 'Rutledge', 'Bekwai', null);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Twitterbridge', 'New Castle', 'Bulungu', null);
