INSERT INTO warehouse (warehouse_name,street,city,sqr_m2, version) VALUES
	 ('Føtex','Jernbanegade','Roskilde',3800, 8),
	 ('Bilka','Torvet','Ishøj',4000, 11),
	 ('Elgiganten','Fabriksparken','Roskilde 3',3400, 8),
	 ('Bauhaus','Industrivej','Roskilde',4500, 5),
	 ('Power','Hovedvejen 123','Glostrup',3500, 4);



insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Zooveo', 'Welch', 'Yoshkar-Ola', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Eayo', 'Welch', 'Aylmer', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Cogidoo', '2nd', 'Jiangzhou', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Linktype', 'Green', 'Baoquan', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Npath', 'Sheridan', 'Riit', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Vinder', 'Artisan', 'Gaizhou', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Tagpad', 'Troy', 'Modis', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Browsebug', 'Esker', 'Cipasung', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Meedoo', 'Dawn', 'Hengjie', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Skynoodle', 'Buhler', 'Castelo', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Minyx', 'Schiller', 'Göteborg', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Youfeed', 'Manitowish', 'Hornówek', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Realmix', 'Meadow Ridge', 'Capatárida', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Rhycero', 'Mosinee', 'Savski Venac', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Quatz', 'Marcy', 'Jinshanzui', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Quire', 'David', 'Buchou', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Zooveo', 'Lerdahl', 'Morong', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Riffpath', 'Truax', 'Barengkok', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Quaxo', 'Grayhawk', 'Svyetlahorsk', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Realfire', 'Lerdahl', 'Lebak', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Plajo', 'Arrowood', 'Amper', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Topicware', 'Rigney', 'Tekikbanyuurip', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Twitterworks', 'Vermont', 'Antonina', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Yacero', 'Rigney', 'Leifeng', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Npath', 'Jana', 'Saint-Rémi', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Skyndu', 'Ridgeview', 'Wushan', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Jaxnation', 'Sachs', 'Rosso', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Blogspan', 'Hermina', 'Babug', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Browsetype', 'Little Fleur', 'Escada', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Jayo', 'Leroy', 'Poá', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Avamba', 'Westerfield', 'Longhua', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Centidel', 'Mockingbird', 'Kanshan', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Lazzy', 'Melrose', 'Gambut', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Thoughtblab', 'Straubel', 'Barcin', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Jabbertype', 'Village Green', 'Lianyun', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Janyx', 'Scoville', 'Daguyun', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Einti', 'Ridgeview', 'Bečej', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Edgeify', 'Sutherland', 'Bistrinci', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Tambee', 'Bartelt', 'Labrador City', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Jaxbean', 'Pepper Wood', 'Antony', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Izio', 'Amoth', 'Iquique', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Photofeed', 'Debra', 'Baikouquan', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Einti', 'Leroy', 'Catujal Velho', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Wikizz', 'Reindahl', 'Al Fandaqūmīyah', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Aimbo', 'Longview', 'Krasnyy Yar', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Mydo', 'Petterle', 'Gąbin', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Plajo', 'Grim', 'Curridabat', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Zoomdog', 'Dexter', 'Di Linh', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Yakijo', 'Bay', 'Rionegro', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Plajo', 'Knutson', 'Ditang', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Browsedrive', 'Holmberg', 'Vicente Guerrero', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Youbridge', 'Tomscot', 'Gucun', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Livefish', 'Prairieview', 'Fuwah', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Skyble', 'Sundown', 'Hallstahammar', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Livetube', 'Ryan', 'Dateng', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Plambee', 'Boyd', 'Ai Tu', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Youopia', 'Roxbury', 'Pantaibesar', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Photojam', 'Susan', 'El Arañado', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Meezzy', 'Nelson', 'Yuanyang Zhen', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Thoughtbridge', 'Eggendart', 'San Francisco', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Trupe', 'Kinsman', 'Erong', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Jetwire', 'Spaight', 'Rancabelut', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Browsebug', 'Muir', 'Camaçari', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Meembee', 'Grover', 'Teupasenti', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Abata', 'Basil', 'Rehoboth', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Geba', 'Grasskamp', 'Prachin Buri', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Viva', 'Manitowish', 'Cangshi', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Meemm', 'Butternut', 'Bolyarovo', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Quinu', 'Stoughton', 'Tambakrejo', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Wordify', 'Trailsway', 'Ubon Ratchathani', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Photojam', 'Bartillon', 'Ciénega', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Eare', 'Sachtjen', 'Kudamatsu', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Centidel', 'Forest Dale', 'Nūrābād', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Eire', 'Ridgeview', 'Longquan', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Bluejam', 'Dovetail', 'Taiping', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Edgepulse', 'Fordem', 'Chengqu', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Plajo', 'Almo', 'Bhamdoûn el Mhatta', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Yodoo', 'Straubel', 'Kotel’va', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Rhycero', 'Leroy', 'Castres', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Riffwire', 'Red Cloud', 'Niš', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Livetube', 'Hauk', 'Sandefjord', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Feedspan', 'Meadow Valley', 'Naro-Fominsk', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Youtags', 'Victoria', 'Lgota Wielka', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Skyba', 'Clemons', 'Gilin', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Browsezoom', 'Golden Leaf', 'Ngepoh Kidul', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Flipstorm', 'Meadow Ridge', 'Kabarnet', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Rhybox', 'Loftsgordon', 'Mólos', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Bluezoom', 'Sundown', 'Hodoš', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Voolith', 'Steensland', 'Xianhe', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Meemm', 'Carey', 'Tolitoli', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Babbleset', 'Fordem', 'Sūq Şirwāḩ', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Cogilith', 'Evergreen', 'Dobřív', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Bubbletube', 'Pond', 'Kónitsa', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Tazz', 'Pawling', 'Cigaleuh Kulon', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Fliptune', 'Cherokee', 'Laixi', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Eabox', 'Donald', 'Tambo', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Browsebug', 'Garrison', 'Lysá nad Labem', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Tagfeed', 'Spohn', 'Pangrumasan', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Yodoo', 'Express', 'Letuyi', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Gabspot', 'Rutledge', 'Bekwai', 0);
insert into tenant_company (company_name, address_street, address_zip_city, version) values ('Twitterbridge', 'New Castle', 'Bulungu', 0);
